version: "3.8"
services:
    stop-fraud:
        container_name: stop-fraud
        build: ../api/
        ports:
        - 8081:80
        volumes:
        - ../api/:/home/stop-fraud
        networks:
        - app_network

    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
        - app_network

    learning-worker:
        container_name: learning-worker
        build: ../learning-worker/
        volumes: 
            - ../learning-worker/:/usr/src/app/
        ports: 
            - 6500:6500
        environment: 
            PORT: 5000
        networks:
        - app_network

networks:
    app_network:
        driver: bridge
